[package]
name = "pyrq_scheduler"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "21.0.2"
chrono = "0.4"
toml = "0.5"
once_cell = "1.8.0"
serde = { version = "1.0.130", features = ["derive"] }
