# In the members below, 'btu_scheduler' is the library.
# The 2 binary applications are btu_cli (alias btu), and btu_daemon

[workspace]
members = [
    "btu_scheduler",
    "btu_cli",
    "btu_daemon",
]
