name: Manually triggered workflow to build binaries

on:
  workflow_dispatch:
    inputs:
      btu_version:
        description: "BTU Semantic Version."
        required: true
      tag:
        description: "Tag of the release"
        required: true

jobs:
  build_ubuntu_20:
    name: Build binaries for Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
      - name: Show GLIBC
        run: ldd --version

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set env on trigger
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "INPUT_TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          echo "BTU_VERSION=${{ github.event.inputs.btu_version }}" >> $GITHUB_ENV

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Rust Binaries
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Create Debian Package
        uses: actions-rs/cargo@v1
        with:
          command: deb
          args: -p btu_scheduler

      - name: Prepare btu-daemon archive
        run: |
          strip target/release/btu-daemon
          export ARCHIVE_NAME_DAEMON=btu-daemon-${{ env.INPUT_TAG }}-linux-x64.tar.gz
          echo "ARCHIVE_NAME_DAEMON=$ARCHIVE_NAME_DAEMON" >> $GITHUB_ENV
          tar -czvf $ARCHIVE_NAME_DAEMON -C target/release btu-daemon

      - name: Prepare btu-cli archive
        run: |
          strip target/release/btu
          export ARCHIVE_NAME_CLI=btu-${{ env.INPUT_TAG }}-linux-x64.tar.gz
          echo "ARCHIVE_NAME_CLI=$ARCHIVE_NAME_CLI" >> $GITHUB_ENV
          tar -czvf $ARCHIVE_NAME_CLI -C target/release btu

      - name: Prepare Debian archive
        run: |
          strip target/debian/btu_scheduler_${{ env.INPUT_TAG }}_amd64.deb
          export ARCHIVE_NAME_DEB=btu_scheduler_${{ env.INPUT_TAG }}_amd64.deb
          echo "ARCHIVE_NAME_DEB=$ARCHIVE_NAME_DEB" >> $GITHUB_ENV

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.INPUT_TAG }}
          release_name: ${{ env.INPUT_TAG }}
          body: HQ ${{ env.INPUT_TAG }}
          draft: false
          prerelease: true

      - name: Upload scheduler daemon binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ARCHIVE_NAME_DAEMON }}
          asset_name: ${{ env.ARCHIVE_NAME_DAEMON }}
          asset_content_type: application/tar+gzip

      - name: Upload CLI binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ARCHIVE_NAME_CLI }}
          asset_name: ${{ env.ARCHIVE_NAME_CLI }}
          asset_content_type: application/tar+gzip

      - name: Upload Debian Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ARCHIVE_NAME_DEB }}
          asset_name: ${{ env.ARCHIVE_NAME_DEB }}
          asset_content_type: application/unknown
